### ISSUE TITLE
Problem with curves

### ISSUE THREAD

**Issue by mlabadie** [openalea-incubator/oawidgets#10] opened 2019-12-05 15:20 UTC
Display problem BezierCurve2D(Point3Array([Vector3(0,0,0),Vector3(0.25,0.75,0),Vector3(0.75,1.25,0),Vector3(1,0.5,0),Vector3(1.25,1,0)]))

**Comment by pradal** [comment] 2021-02-25 10:44
@pomme-abricot Add an fix in PlantGL when it is a curve.
Then found the equivalent function in k3d to draw a Bezier curve

**Comment by pradal** [comment] 2021-02-25 10:46
To plot a line use: https://k3d-jupyter.org/basic_functionality/Line.html

**Comment by pradal** [comment] 2021-02-25 10:55
For curves: (geom.isACurve()) 
d = Discretizer()
status = crv.apply(d)

d.result.pointList

**Comment by pomme-abricot** [comment] 2021-03-02 17:02
I fixed the 3D problem with PlantGL when using group_by_color=True.
The scene and curves are not separated when group_by_color=False.

**Comment by pradal** [comment] 2021-03-22 22:11
@pomme-abricot : If it is solved, close the issue

**Comment by pomme-abricot** [comment] 2021-03-23 08:39
The problem is fixed only in 3D & using group_by_color=True.
Still not working on 2D scenes

**Closed** 2021-04-09 13:14 UTC
